using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class ScriptGenerator : MonoBehaviour
{
    public bool makeScript = false;
    
    // Start is called before the first frame update
    void Update()
    {
        if(makeScript || ((Input.GetKey(KeyCode.LeftControl)||Input.GetKey(KeyCode.RightControl))&&Input.GetKeyDown(KeyCode.S)))
        {
            MakeScript();
            makeScript = false;
        }
    }


    public void MakeScript()
    {
        Debug.Log("Making Script...");
        

        var fileWriter = new StreamWriter(SceneManager.DclProjectPath + "/src/scene.ts", false);
        fileWriter.WriteLine("// GENERATED BY DCL-EDIT\n// DO NOT MODIFY\n");

        foreach (var entity in SceneManager.Entities)
        {
            fileWriter.WriteLine(entity.GetTypeScript());
        }


        fileWriter.Close();
    }
}
