using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class ScriptGenerator : MonoBehaviour
{
    public bool makeScript = false;
    
    // Start is called before the first frame update
    void Update()
    {
        if(makeScript)
        {
            MakeScript();
            makeScript = false;
        }
    }

    public struct ExposedVars
    {
        public string exposedAs;
        public string symbol;
    }

    public static string GetTypeScriptForEntity(Entity entity, ref List<ScriptGenerator.ExposedVars> exposed)
    {
        var script = $"const {entity.InternalSymbol} = new Entity(\"{entity.ShownName}\")\n";
        script += $"engine.addEntity({entity.InternalSymbol})\n";

        var exposedVar = new ScriptGenerator.ExposedVars
        {
            exposedAs = "entity",
            symbol = entity.InternalSymbol
        };
        exposed.Add(exposedVar);

        foreach (var component in entity.Components)
        {
            var componentTs = component.GetTypeScript();
            script += componentTs.setup;
            script += $"{entity.InternalSymbol}.addComponentOrReplace({componentTs.symbol})\n";

            var exposedComponentVar = new ScriptGenerator.ExposedVars
            {
                exposedAs = component.ComponentName,
                symbol = componentTs.symbol
            };
            exposed.Add(exposedComponentVar);
        }
        
        return script;
    }

    public static void MakeScript()
    {
        Debug.Log("Making Script...");
        

        var fileWriter = new StreamWriter(SceneManager.DclProjectPath + "/src/scene.ts", false);
        fileWriter.WriteLine("// GENERATED BY DCL-EDIT\n// DO NOT MODIFY\n");

        var allExposedVars = new Dictionary<string, List<ExposedVars>>();

        foreach (var entity in SceneManager.Entities)
        {
            var exposedVars = new List<ExposedVars>();
            fileWriter.WriteLine(GetTypeScriptForEntity(entity,ref exposedVars));

            if(entity.Exposed)
            {
                allExposedVars.Add(entity.ExposedSymbol, exposedVars);
            }
        }

        fileWriter.WriteLine("export let scene = {");

        foreach (var exposedVars in allExposedVars)
        {
            fileWriter.WriteLine("  " + exposedVars.Key + ":{");

            foreach (var variable in exposedVars.Value)
            {
                fileWriter.WriteLine($"    {variable.exposedAs}: {variable.symbol},");
            }

            fileWriter.WriteLine("  },");
        }

        fileWriter.WriteLine("}\n");


        fileWriter.Close();
    }
}
